[tool.poetry]
name = "projetos-conjunto"
version = "0.1.0"
description = "Projeto de pipeline de Modelos"
authors = ["VitorrSantana <vitorsantanacasa357@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
polars = "^1.26.0"
pandas = "^2.2.3"
pre-commit = "^4.2.0"
streamlit = "^1.45.1"
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
