name: Pipeline
on: [push,pull_request]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Clone dos Arquivos dos Projetos
        uses: actions/checkout@v4
      
      - name: Lista Arquivos Diretorio
        run: echo $(ls)